name: godeps-guard

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run godeps-guard
        uses: ./
        with:
          base-ref: origin/${{ github.base_ref }}
          config-file: .godepsguard.yaml
